### ISSUE TITLE
Dasiamrpn

### ISSUE THREAD

**Issue by Artem-N** [Kazuhito00/OpenCV-Object-Tracker-Python-Sample#5]
Hi, great work, looking at your code in general is a pleasure to the eyes. 

I have a question - I want to automatically detect an object and transfer the coordinates of the detected object to the tracker, I install ultralytics and use Yolo11, all trackers work well except for "dasiamrpn".
As soon as the detector transmits the coordinate, it does not work anymore, that is, the computation is all on the tracker, but this particular tracker works very slowly for me. Is it possible to launch this particular tracker quickly in this way? 
Thank you!

**Comment by Kazuhito00** [comment]
Sorry, I don't know how to speed it up.
